apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chaos-mesh
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://charts.chaos-mesh.org
      chart: chaos-mesh
      targetRevision: 2.8.3
      helm:
        releaseName: chaos-mesh
        valueFiles:
          - $values/deploy/helm/chaos-mesh-values.yaml
    - repoURL: https://github.com/luizgnz/chessforge.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: chaos-mesh
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
