apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: chessforge-db
  namespace: chessforge
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: chessforge-db
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: chessforge/db
        property: DATABASE_URL
    - secretKey: password
      remoteRef:
        key: chessforge/db
        property: password
    - secretKey: postgres-password
      remoteRef:
        key: chessforge/db
        property: postgres-password
