apiVersion: v1
kind: Service
metadata:
  name: analyzer
  namespace: chessforge
  labels:
    app: analyzer
spec:
  type: ClusterIP
  selector:
    app: analyzer
  ports:
    - name: metrics
      port: 9090
      targetPort: metrics
      protocol: TCP
