apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chessforge-root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/luizgnz/chessforge.git
    targetRevision: HEAD
    path: deploy/gitops/applications
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
